#!/bin/sh

LANG=C

#LINUX_TOP=../JunkBox_Lib/C++Lib
LINUX_TOP=../../linux/JunkBox_Lib/C++Lib
WIN_TOP=.


copy2win()
{
    LF=$LINUX_TOP/$1
    WF=$WIN_TOP/$2

    if [ ! -f $WF ]; then
        return
    fi

    #nkf -s $LF >| $WF
    cp -f  $LF $WF
    echo "update "$WF
}


diffwin()
{
    LF=$LINUX_TOP/$1
    WF=$WIN_TOP/$1

    if [ ! -f $WF ]; then
        return
    fi

    #nkf -s $LF >| $LF.temp
    diff -q $LF $WF | awk -F" " '{print $4}'
    #rm -rf  $LF.temp
}


diffwin_c()
{
    LF=$LINUX_TOP/$1
    WF=`echo $WIN_TOP/$1 | sed s/\.c$/\.cpp/`

    if [ ! -f $WF ]; then
        return
    fi

    #nkf -s $LF >| $LF.temp
    diff -q $LF $WF | awk -F" " '{print $4}' | sed s/\.cpp$/\.c/
    #rm -rf  $LF.temp
}



LN=`echo $1 | sed s/\.cpp$/\.c/`
copy2win $LN $1



